{
    "openapi": "3.0.0",
    "info": {
        "title": "Simple OAI 3.0.0 API",
        "version": "2.0.11",
        "description": "A simple API using OpenAPI 3.0.0.",
        "contact": {
            "name": "Example Org",
            "url": "http://www.example.org",
            "email": "contact@example.org"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "https://www.apache.org/licenses/LICENSE-2.0"
        }
    },
    "paths": {
        "/": {
            "get": {
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "examples": {
                                    "foo": {
                                        "value": {
                                            "versions": [
                                                {
                                                    "status": "CURRENT",
                                                    "updated": "2011-01-21T11:33:21Z",
                                                    "id": "v2.0",
                                                    "links": [
                                                        {
                                                            "href": "http://127.0.0.1:8774/v2/",
                                                            "rel": "self"
                                                        }
                                                    ]
                                                },
                                                {
                                                    "status": "EXPERIMENTAL",
                                                    "updated": "2013-07-23T11:33:21Z",
                                                    "id": "v3.0",
                                                    "links": [
                                                        {
                                                            "href": "http://127.0.0.1:8774/v3/",
                                                            "rel": "self"
                                                        }
                                                    ]
                                                }
                                            ]
                                        }
                                    }
                                }
                            }
                        },
                        "description": "200 response"
                    },
                    "300": {
                        "content": {
                            "application/json": {
                                "examples": {
                                    "foo": {
                                        "value": "{\n \"versions\": [\n       {\n         \"status\": \"CURRENT\",\n         \"updated\": \"2011-01-21T11:33:21Z\",\n         \"id\": \"v2.0\",\n         \"links\": [\n             {\n                 \"href\": \"http://127.0.0.1:8774/v2/\",\n                 \"rel\": \"self\"\n             }\n         ]\n     },\n     {\n         \"status\": \"EXPERIMENTAL\",\n         \"updated\": \"2013-07-23T11:33:21Z\",\n         \"id\": \"v3.0\",\n         \"links\": [\n             {\n                 \"href\": \"http://127.0.0.1:8774/v3/\",\n                 \"rel\": \"self\"\n             }\n         ]\n     }\n ]\n}\n"
                                    }
                                }
                            }
                        },
                        "description": "300 response"
                    }
                },
                "operationId": "listVersionsv2",
                "summary": "List API versions"
            }
        },
        "/v2": {
            "get": {
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "examples": {
                                    "foo": {
                                        "value": {
                                            "version": {
                                                "status": "CURRENT",
                                                "updated": "2011-01-21T11:33:21Z",
                                                "media-types": [
                                                    {
                                                        "base": "application/xml",
                                                        "type": "application/vnd.openstack.compute+xml;version=2"
                                                    },
                                                    {
                                                        "base": "application/json",
                                                        "type": "application/vnd.openstack.compute+json;version=2"
                                                    }
                                                ],
                                                "id": "v2.0",
                                                "links": [
                                                    {
                                                        "href": "http://127.0.0.1:8774/v2/",
                                                        "rel": "self"
                                                    },
                                                    {
                                                        "href": "http://docs.openstack.org/api/openstack-compute/2/os-compute-devguide-2.pdf",
                                                        "type": "application/pdf",
                                                        "rel": "describedby"
                                                    },
                                                    {
                                                        "href": "http://docs.openstack.org/api/openstack-compute/2/wadl/os-compute-2.wadl",
                                                        "type": "application/vnd.sun.wadl+xml",
                                                        "rel": "describedby"
                                                    },
                                                    {
                                                        "href": "http://docs.openstack.org/api/openstack-compute/2/wadl/os-compute-2.wadl",
                                                        "type": "application/vnd.sun.wadl+xml",
                                                        "rel": "describedby"
                                                    }
                                                ]
                                            }
                                        }
                                    }
                                }
                            }
                        },
                        "description": "200 response"
                    },
                    "203": {
                        "content": {
                            "application/json": {
                                "examples": {
                                    "foo": {
                                        "value": {
                                            "version": {
                                                "status": "CURRENT",
                                                "updated": "2011-01-21T11:33:21Z",
                                                "media-types": [
                                                    {
                                                        "base": "application/xml",
                                                        "type": "application/vnd.openstack.compute+xml;version=2"
                                                    },
                                                    {
                                                        "base": "application/json",
                                                        "type": "application/vnd.openstack.compute+json;version=2"
                                                    }
                                                ],
                                                "id": "v2.0",
                                                "links": [
                                                    {
                                                        "href": "http://23.253.228.211:8774/v2/",
                                                        "rel": "self"
                                                    },
                                                    {
                                                        "href": "http://docs.openstack.org/api/openstack-compute/2/os-compute-devguide-2.pdf",
                                                        "type": "application/pdf",
                                                        "rel": "describedby"
                                                    },
                                                    {
                                                        "href": "http://docs.openstack.org/api/openstack-compute/2/wadl/os-compute-2.wadl",
                                                        "type": "application/vnd.sun.wadl+xml",
                                                        "rel": "describedby"
                                                    }
                                                ]
                                            }
                                        }
                                    }
                                }
                            }
                        },
                        "description": "203 response"
                    }
                },
                "operationId": "getVersionDetailsv2",
                "summary": "Show API version details"
            },
            "put": {
                "requestBody": {
                    "description": "A description of the request body goes here.",
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/User"
                            }
                        }
                    },
                    "required": true
                },
                "responses": {
                    "200": {

                    }
                },
                "summary": "Update API version details"
            }
        }
    },
    "components": {
        "schemas": {
            "AddressList": {
                "properties": {
                    "address": {
                        "$ref": "#/components/schemas/Subtractress"
                    }
                }
            },
            "User": {
                "properties": {
                    "address": {
                        "$ref": "#/components/schemas/Subtractress",
                        "description": "Foo foo foo."
                    }
                }
            },
            "Subtractress": {
                "properties": {
                    "name": {

                    },
                    "street": {

                    },
                    "city": {

                    },
                    "state": {

                    },
                    "zip": {

                    }
                }
            }
        }
    }
}